/*
 * generated by Xtext 2.25.0
 */
package fr.unice.cotedazur.l3ia.chart.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
