/*
 * generated by Xtext 2.25.0
 */
package fr.unice.cotedazur.l3ia.chart;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
