/*
 * generated by Xtext 2.25.0
 */
package fr.unice.cotedazur.l3ia.chart.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/unice/cotedazur/l3ia/chart/parser/antlr/internal/InternalMyDsl.tokens");
	}
}
