/*
 * generated by Xtext 2.25.0
 */
package fr.unice.cotedazur.l3ia.chart.ui.tests;

import com.google.inject.Injector;
import fr.unice.cotedazur.l3ia.chart.ui.internal.ChartActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ChartActivator.getInstance().getInjector("fr.unice.cotedazur.l3ia.chart.MyDsl");
	}

}
