/*
 * generated by Xtext 2.25.0
 */
package fr.unice.cotedazur.l3ia.chart.ui;

import com.google.inject.Injector;
import fr.unice.cotedazur.l3ia.chart.ui.internal.ChartActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ChartActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ChartActivator activator = ChartActivator.getInstance();
		return activator != null ? activator.getInjector(ChartActivator.FR_UNICE_COTEDAZUR_L3IA_CHART_MYDSL) : null;
	}

}
